# Generated by Django 5.2.15 on 2026-06-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/images/")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=200)),
                ("links", models.URLField(blank=True, default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(upload_to="services/icons/")),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
    ]
